version: "3.8"

services:
  test-man-api:
    build:
      context: test-man-api
      dockerfile: Dockerfile
      #dockerfile: runOnly.Dockerfile
    ports:
      - "8080:8080"

  test-man-ui:
    build:
      context: test-man-ui
      dockerfile: Dockerfile
      #dockerfile: runOnly.Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - test-man-api
